dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  postgres: ^2.6.3
  twilio_flutter: ^0.0.9
  shared_preferences: ^2.2.2
  flutter_dotenv: ^5.1.0
  crypto: ^3.0.3
  # ... existing dependencies

# ... rest of the file remains same 