name: farmer_marketplace
description: A direct farmer-to-consumer marketplace application.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  postgres: ^2.6.3
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  shared_preferences: ^2.2.2
  flutter_dotenv: ^5.1.0
  path_provider: ^2.1.2
  cupertino_icons: ^1.0.6
  uuid: ^4.2.1         # For generating unique IDs
  intl: ^0.19.0        # For date formatting
  google_fonts: ^6.1.0 # For custom fonts
  flutter_secure_storage: ^9.0.0  # For secure storage of sensitive data
  cached_network_image: ^3.3.0    # For image caching
  geolocator: ^10.1.0  # For location services
  http: ^1.1.2         # For HTTP requests

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  test: ^1.24.9
  mockito: ^5.4.4
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  
  assets:
    - .env
    - assets/images/
    - assets/icons/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300